### ISSUE TITLE
Beer JS Voronezh #1

### ISSUE THREAD

**Issue by fxlrnrpt** [beerjs/voronezh#1]
21 декабря 2019
13:00
[Бар НЗБ](https://go.2gis.com/cwvyb)

Форма для регистрации: https://js-monkeys-vrn.timepad.ru/event/1134506/

Темы докладов:
1. **Тема**: React: работа с формами в 2020 (ну, почти)
    **Описание**: Рассмотрим популярные решения для работы с формами, пробежимся по API, погоняем бенчмарки и разберемся с тем, как этот зоопарк тестировать.
    **Докладчик**: Гончаров Андрей, Software Engineer, @hazelcast ( @aigoncharov )
1. **Тема**: Немного шалим со свежими WeakRef и FinalizationGroup API
    **Описание**: WeakRef и FinalizationGroup находятся на Stage 3 в TC39 и нам, похоже, уже их не избежать. Поэтому самое время с ними внимательно познакомиться. Начнем с истории вопроса, поговорим о простых примерах и, наконец, посмотрим на экспериментальную реализацию Buffer pool для Node.js на основе FinalizationGroup.
    **Докладчик**: Печкуров Андрей, Software Engineer, @hazelcast ( @puzpuzpuz  )
1. **Тема**: У себя мы называем его вуй
    **Описание**: Расскажу о моем опыте в одном из первых проектов на Vue.js. Опишу подводные камни, покажу на какие грабли я наступил, дам рекомендации как не повторить моих ошибок.
    **Докладчик**: Корянов Василий, Frontend Developer, @Voximplant ( @grindpride  )
1. **Тема**: Развлекаемся на JS
    **Описание**: Расскажу про то, как программирование может быть основной игровой механикой, почему это интересно и какая от этого может быть польза.
    **Докладчик**: Николай Харитонов, Game Designer and Developer, @Screeps ( @o4kapuk  )

Желающие выступить могут писать на почту andrey@goncharov.page, в телеграм https://t.me/ai_goncharov или в эту ишшу.

P.S. Присоединяйтесь к нашему уютному ламповому чатику - https://t.me/beer_js_voronezh

**Comment by fxlrnrpt** [comment]
@khusnetdinov @ivanzotov @stereodenis @ykhrustalev @Red-Cat-Fat @serge1peshcoff @kashesandr @zhrivodkin @Ser-Gen @amelekhin @vjik @IwalkAlone @qxuken @jsperov @fortSQ @i-madness @LeeSwagger @DmitryMiroshnichenko @atwaves  @EA5 @vladcyb @erizoy @eunikitin @andreysaleba @oneusha @artemwolf @alex-panin @nikches @voronina-ai 
@glavmaxim @voodoo-project @acupofspirt @aturbidflow @AntonVoronezh @nik48rus @aleyakovle @flashnot @staleo @altukhov-a @pechatnov @MG-Pro @zloyXPEH 
@SergeyUkolov @romangordeew @semyenov @Leg1onary @den-efremov @lesson-web @nikitj 
@DevToolz

Приходите на первый в Воронеже BeerJS!

**Comment by fxlrnrpt** [comment]
@qxlab @MrLyapin @alexey-tyulkin @zhdanovasofi @abc-z @yurylunev @skyeselv @iDarkLord @hpdmitriy @slavafedoseev @qbWithYou @factorymn @newpdv @IgorPerelyotov 
@Alexander091 @shamanomania @ukolovpk @YrpIOMbI4 @KaguraDun @fuckinet @NarineSamveli @bd667 @temich0808 @denipotapo @MaksimovAV @Niko-lie @Tatasik @AlexPsilon @999-Victor @wishhaze @mloolm @StasTet @dpischalka @spy4x @GlshchnkLx 
@Rombique @savvinsergey @good-news-everyone @del333ted

Приходите на первый в Воронеже BeerJS!

**Comment by ykhrustalev** [comment]
@khorpy

**Comment by fxlrnrpt** [comment]
Расписание докладов:
13 00 - 13 40 - "У себя мы называем его вуй", Корянов Василий
13 45 - 14 25 - "React: работа с формами в 2020 (ну, почти)", Гончаров Андрей
14 30 - 15 10 - "Немного шалим со свежими WeakRef и FinalizationGroup API", Печкуров Андрей
15 20 - 15 50 - "Развлекаемся на JS", Николай Харитонов

Внимание! Расписание может измениться! Подписывайтесь на эту ишшу, чтобы оставаться в курсе!

**Comment by fxlrnrpt** [comment]
Ребята, спасибо всем, кто пришел!
Слайды опубликованы в телеграм https://t.me/beer_js_voronezh.
Пассивно ищутся спикеры на следущий митап! Как только набираем 3 желающих - стартуем!
Уже известно, что Николай расскажет нам про геймдев в js. Осталось ещё два слота. Желающие - в личку в телеграм (@ai_goncharov) или на почту (andrey@goncharov.page). Просьба планировать свои доклады на 30 минут без учёта вопросов.
