### ISSUE TITLE
Beer JS Voronezh #2

### ISSUE THREAD

**Issue by fxlrnrpt** [beerjs/voronezh#2]
5 февраля 2020 (среда)
19:00
[Бар НЗБ](https://go.2gis.com/cwvyb)

Темы докладов:
1. **Тема: Развлекаемся на JS**
    **Описание**: Расскажу про то, как программирование может быть основной игровой механикой, почему это интересно и какая от этого может быть польза.
    **Докладчик**: Николай Харитонов, Game Designer and Developer, @Screeps ( @o4kapuk  )
1. **Тема: Strict mode in TypeScript or help your compiler help you**
    **Описание**: Компилятор TypeScript предоставляет более 90 флагов. 7 из них известны как "strict". 1 предназначен для того, чтобы управлять ими всеми.
В рамках доклада мы пробежимся по все 7 опциям, разберем, что они должны делать в теории. Рассмотрим код реальных приложений и случаи, когда "strict" режим может спасти нам множество нервных клеток.
    **Докладчик**: Гончаров Андрей, Software Engineer, @Hazelcast ( @aigoncharov   )
1. **Тема: Небольшая история про SEO продвижение React приложения**
    **Описание**: Расскажу как я со своей командой на проекте подружил кодовую базу обычного SPA на React с GatsbyJS и других мелочах, дабы улучшить показатели выдачи контента платформы в поисковиках
    **Докладчик**: Казарян Артем, Full-stack dev, @DSRCorporation ( @boombang   )
1. **Тема: Bug busters или Фантастические т̶в̶а̶р̶и̶ баги**
    **Описание**: Рассмотрим подходы к тестированию со стороны фронт-энда, что стоит использовать, а от чего пользы можно не дождаться.
    **Докладчик**: Еникеев Роман, Development Lead, @DataArt

P.S. Присоединяйтесь к нашему уютному ламповому чатику - https://t.me/beer_js_voronezh

**Comment by aigoncharov** [comment]
На митапе будет разыграна кружка с нашим новым лого <img src="https://github.com/beerjs/voronezh/blob/master/beerjsvrn.jpg">

**Comment by fxlrnrpt** [comment]
Расписание:
- 19:00 - 19:10 - Открытие
- 19:10 - 19:40 - "Развлекаемся на JS", Николай Харитонов, Screeps
- 19:50 - 20:20 - "Небольшая история про SEO продвижение React приложения", Казарян Артем, DSR Corporation
- 20:30 - 21:00 - "Bug busters или Фантастические т̶в̶а̶р̶и̶ баги", Еникеев Роман, DataArt
- 21:10 - 21:40 - "Strict mode in TypeScript or help your compiler help you", Гончаров Андрей, Hazelcast
